data:
  source: yfinance    
  ticker1: XOM
  ticker2: CVX
  csv1: null
  csv2: null
  start: "2018-01-01"
  end: null
  price_col: "Adj Close"
  freq: "B"

strategy:
  lookback: 60
  entry: 2.0
  exit: 0.0
  max_abs_z: 4.0
  cooldown: 2

execution:
  tc_bps: 1.0
  slippage_bps: 0.5
  short_borrow_apr: 0.02
  capital: 1000000
  signal_delay: 1
  periods_per_year: 252
